// Code generated by yo. DO NOT EDIT.
package repository

import (
	"cloud.google.com/go/spanner"
)

type AllRepository struct {
	Group     GroupRepository
	UserGroup UserGroupRepository
	User      UserRepository
}

func NewAllRepository(client *spanner.Client) *AllRepository {
	return &AllRepository{
		NewGroupRepository(client),
		NewUserGroupRepository(client),
		NewUserRepository(client),
	}
} //
