// Code generated by yo. DO NOT EDIT.
package repository

type GroupRepository interface {
	GroupRepositoryIndexes
	GroupRepositoryCRUD
}

type UserGroupRepository interface {
	UserGroupRepositoryIndexes
	UserGroupRepositoryCRUD
}

type UserRepository interface {
	UserRepositoryIndexes
	UserRepositoryCRUD
} //
