// Code generated by yo. DO NOT EDIT.
package repository

type GroupRepositoryGenerated interface {
	GroupRepositoryIndexes
	GroupRepositoryCRUD
	GroupRepositoryUtil
}

type UserGroupRepositoryGenerated interface {
	UserGroupRepositoryIndexes
	UserGroupRepositoryCRUD
	UserGroupRepositoryUtil
}

type UserRepositoryGenerated interface {
	UserRepositoryIndexes
	UserRepositoryCRUD
	UserRepositoryUtil
} //
