// Code generated by yo. DO NOT EDIT.
package repository

import (
	"context"

	"github.com/s-you/yo-templates/internal/model"
)

type GroupRepositoryIndexes interface {
	GetGroupByGroupID(ctx context.Context, groupID string) (*model.Group, error)
	FindGroupByGroupIDs(ctx context.Context, ids []string) ([]*model.Group, error)
}

// GetGroupByGroupID retrieves a row from 'groups' as a Group.
// Generated from primary key
func (g groupRepository) GetGroupByGroupID(ctx context.Context, groupID string) (*model.Group, error) {
	group := &model.Group{}
	if err := g.Builder().
		Where("group_id = @param0", Params{"param0": groupID}).
		Query(ctx).Into(group); err != nil {
		return nil, err
	}

	return group, nil
}

// FindGroupByGroupIDs retrieves multiple rows from 'groups' as []*model.Group.
// Generated from primary key
func (g groupRepository) FindGroupByGroupIDs(ctx context.Context, ids []string) ([]*model.Group, error) {
	var items []*model.Group
	if err := g.Builder().Where("group_id IN UNNEST(?)", ids).Query(ctx).Intos(&items); err != nil {
		return nil, err
	}

	return items, nil
}

type UserRepositoryIndexes interface {
	GetUserByUserID(ctx context.Context, userID string) (*model.User, error)
	FindUserByUserIDs(ctx context.Context, ids []string) ([]*model.User, error)
	FindUsersByName(ctx context.Context, name string) ([]*model.User, error)
	FindUsersByNames(ctx context.Context, ids []string) ([]*model.User, error)
}

// GetUserByUserID retrieves a row from 'users' as a User.
// Generated from primary key
func (u userRepository) GetUserByUserID(ctx context.Context, userID string) (*model.User, error) {
	user := &model.User{}
	if err := u.Builder().
		Where("user_id = @param0", Params{"param0": userID}).
		Query(ctx).Into(user); err != nil {
		return nil, err
	}

	return user, nil
}

// FindUserByUserIDs retrieves multiple rows from 'users' as []*model.User.
// Generated from primary key
func (u userRepository) FindUserByUserIDs(ctx context.Context, ids []string) ([]*model.User, error) {
	var items []*model.User
	if err := u.Builder().Where("user_id IN UNNEST(?)", ids).Query(ctx).Intos(&items); err != nil {
		return nil, err
	}

	return items, nil
}

type UserGroupRepositoryIndexes interface {
	GetUserGroupByGroupIDAndUserID(ctx context.Context, groupID string, userID string) (*model.UserGroup, error)
	FindUserGroupsByUserID(ctx context.Context, userID string) ([]*model.UserGroup, error)
	FindUserGroupsByUserIDs(ctx context.Context, ids []string) ([]*model.UserGroup, error)
}

// GetUserGroupByGroupIDAndUserID retrieves a row from 'user_groups' as a UserGroup.
// Generated from primary key
func (ug userGroupRepository) GetUserGroupByGroupIDAndUserID(ctx context.Context, groupID string, userID string) (*model.UserGroup, error) {
	userGroup := &model.UserGroup{}
	if err := ug.Builder().
		Where("group_id = @param0 AND user_id = @param1", Params{"param0": groupID, "param1": userID}).
		Query(ctx).Into(userGroup); err != nil {
		return nil, err
	}

	return userGroup, nil
}

// GetUsersByName retrieves multiple rows from 'users' as a slice of User.
// Generated from index 'idx_users_name'.
func (u userRepository) FindUsersByName(ctx context.Context, name string) ([]*model.User, error) {
	user := []*model.User{}
	if err := u.Builder().
		Where("name = @param0", Params{"param0": name}).
		Query(ctx).Intos(&user); err != nil {
		return nil, err
	}

	return user, nil
}

// FindUsersByNames retrieves multiple rows from 'users' as []*model.User.
// Generated from unique index 'idx_users_name'.
func (u userRepository) FindUsersByNames(ctx context.Context, ids []string) ([]*model.User, error) {
	var items []*model.User
	if err := u.Builder().Where("name IN UNNEST(?)", ids).Query(ctx).Intos(&items); err != nil {
		return nil, err
	}

	return items, nil
}

// GetUserGroupsByUserID retrieves multiple rows from 'user_groups' as a slice of UserGroup.
// Generated from index 'idx_group_users_user_id'.
func (ug userGroupRepository) FindUserGroupsByUserID(ctx context.Context, userID string) ([]*model.UserGroup, error) {
	userGroup := []*model.UserGroup{}
	if err := ug.Builder().
		Where("user_id = @param0", Params{"param0": userID}).
		Query(ctx).Intos(&userGroup); err != nil {
		return nil, err
	}

	return userGroup, nil
}

// FindUserGroupsByUserIDs retrieves multiple rows from 'user_groups' as []*model.UserGroup.
// Generated from unique index 'idx_group_users_user_id'.
func (ug userGroupRepository) FindUserGroupsByUserIDs(ctx context.Context, ids []string) ([]*model.UserGroup, error) {
	var items []*model.UserGroup
	if err := ug.Builder().Where("user_id IN UNNEST(?)", ids).Query(ctx).Intos(&items); err != nil {
		return nil, err
	}

	return items, nil
}
