// Code generated by yo. DO NOT EDIT.
package repository

/*

type GroupRepository interface {
	GroupRepositoryGenerated
}

type UserGroupRepository interface {
	UserGroupRepositoryGenerated
}

type UserRepository interface {
	UserRepositoryGenerated
}
*/ //
