// Code generated by yo. DO NOT EDIT.
// Package model contains the types.
package model

import (
	"github.com/google/uuid"
)

func NewUUID() (string, error) {
	id, err := uuid.NewRandom()
	if err != nil {
		return "", err
	}
	return id.String(), nil
}

func (g *Group) SetIdentity() (err error) {
	if g.GroupID == "" {
		g.GroupID, err = NewUUID()
	}
	return
}

func (u *User) SetIdentity() (err error) {
	if u.UserID == "" {
		u.UserID, err = NewUUID()
	}
	return
}

func (ug *UserGroup) SetIdentity() (err error) {
	return
}
