// Code generated by yo. DO NOT EDIT.
package {{ .Package }}
{{- range $k, $v := .TableMap }}

type {{$v.Name}}RepositoryGenerated interface {
	{{$v.Name}}RepositoryIndexes
	{{$v.Name}}RepositoryCRUD
	{{$v.Name}}RepositoryUtil
}
{{- end }}
{{- /* */ -}}
