// Code generated by yo. DO NOT EDIT.
package {{ .Package }}

import (
	"bytes"
	"context"
	"encoding/binary"
	"encoding/gob"

	"cloud.google.com/go/spanner"

	"github.com/cespare/xxhash"
	"github.com/s-you/yo-templates/internal/middleware"
	"github.com/s-you/yo-templates/internal/model"
)

func getCacheKey(stmt spanner.Statement) (string, error) {
	sum64 := xxhash.Sum64String(stmt.SQL)
	buf := new(bytes.Buffer)
	cacheKey := make([]byte, 8)
	binary.LittleEndian.PutUint64(cacheKey, sum64)
	buf.Write(cacheKey)
	e := gob.NewEncoder(buf)
	err := e.Encode(stmt.Params)
	if err != nil {
		return "", err
	}
	return buf.String(), nil
}
{{- /* */ -}}
