{{- $maxLen := 0 }}
{{- range $k, $v := .TableMap }}
	{{- if lt $maxLen (len $v.Name)}}{{$maxLen = len $v.Name}}{{ end }}
{{- end -}}

// Code generated by yo. DO NOT EDIT.
package {{ .Package }}

import (
	"cloud.google.com/go/spanner"
)

type AllRepository struct {
{{- range $k, $v := .TableMap }}
	{{printf "%-*s" $maxLen $v.Name}} {{$v.Name}}Repository
{{- end }}
	Repository
}

func NewAllRepository(client *spanner.Client) *AllRepository {
	return &AllRepository{
		{{- range $k, $v := .TableMap }}
		New{{$v.Name}}Repository(client),
		{{- end }}
		NewRepository(client),
	}
}
{{- /* */ -}}
