// Code generated by yo. DO NOT EDIT.
// Package {{ .Package }} contains the types.
package {{ .Package }}

import (
	"context"
	"fmt"
	"time"

	"cloud.google.com/go/spanner"
	"github.com/s-you/yo-templates/internal/util"
)

type H = map[string]interface{}
